<?php
/**
 * AdOcean Configuration
 *
 * parsed from /home/web/o24.blrf.net/wp-content/themes/n24tv/include/ads/ads.txt @ 2017-03-11 21:09:53
 *
 * Locations were mapped from: 
 * oglasno ozadje => background
 * 728x90 spodaj => bottom
 * billboard zgoraj => billboard
 * billboard => billboard
 * 300x250 desno => sidebar-top
 * 300x250 zgoraj => sidebar-top
 * 300x250 desno zgoraj => sidebar-top
 * 728x90 zgoraj => upper
 * banderola => banderola
 * 728x90 pod rubriko Novice => front-page-novice
 * 728x90 pod rubriko _port => front-page-sport
 * 300x250 spodaj => sidebar-bottom
 * 300x250 desno spodaj => sidebar-bottom
 * floater => floater
 * preroll video => preroll-video
 * 300x250 pod _lankom => single-bottom
 * 728x90 nad komentarji => single-comment
 *
 */

$adoceanConfig = array(
'front-page' => array(
	'background' => array('slave_id' => 'adoceansiygeldrdhqu', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'bottom' => array('slave_id' => 'adoceansivhlrgonlpp', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'billboard' => array('slave_id' => 'adoceansisiciklhqvk', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'sidebar-top' => array('slave_id' => 'adoceansiuajimpjocy', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'upper' => array('slave_id' => 'adoceansivncjlmmlgf', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'banderola' => array('slave_id' => 'adoceansilihlnoducr', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'front-page-novice' => array('slave_id' => 'adoceansilmntqmlrad', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'front-page-sport' => array('slave_id' => 'adoceansiymekekfgqc', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansimartbpmizm', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
	'floater' => array('slave_id' => 'adoceansiyaglioomei', 'master_id' => 'WGCqmU3GA4vLNLfOPXp7F5vd7iL_gZtSPgxbsdHYtGv.d7'),
),
'c:slovenija' => array(
	'banderola' => array('slave_id' => 'adoceansizokhoqjfpp', 'master_id' => '_3sFAac27VmfUPB_4iwGMVmGoypQ0ZIr9RnJeXryE1z.j7'),
	'billboard' => array('slave_id' => 'adoceansiwprnbodkkk', 'master_id' => '_3sFAac27VmfUPB_4iwGMVmGoypQ0ZIr9RnJeXryE1z.j7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansimeliproqmg', 'master_id' => '_3sFAac27VmfUPB_4iwGMVmGoypQ0ZIr9RnJeXryE1z.j7'),
	'sidebar-top' => array('slave_id' => 'adoceansizecpcpifrf', 'master_id' => '_3sFAac27VmfUPB_4iwGMVmGoypQ0ZIr9RnJeXryE1z.j7'),
	'bottom' => array('slave_id' => 'adoceansiwfjfgmsjba', 'master_id' => '_3sFAac27VmfUPB_4iwGMVmGoypQ0ZIr9RnJeXryE1z.j7'),
	'upper' => array('slave_id' => 'adoceansitgqljjmolv', 'master_id' => '_3sFAac27VmfUPB_4iwGMVmGoypQ0ZIr9RnJeXryE1z.j7'),
	'background' => array('slave_id' => 'adoceansiqhhsmwftvq', 'master_id' => '_3sFAac27VmfUPB_4iwGMVmGoypQ0ZIr9RnJeXryE1z.j7'),
	'floater' => array('slave_id' => 'adoceansiyngsorlgya', 'master_id' => '_3sFAac27VmfUPB_4iwGMVmGoypQ0ZIr9RnJeXryE1z.j7'),
),
'c:svet' => array(
	'banderola' => array('slave_id' => 'adoceansizcothoomwb', 'master_id' => '9zuVcerD7RjP.8_jFEATbD107IeWoF.z2BHv5Dx2LqX.G7'),
	'billboard' => array('slave_id' => 'adoceansiwdfkllircw', 'master_id' => '9zuVcerD7RjP.8_jFEATbD107IeWoF.z2BHv5Dx2LqX.G7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiomribwqotu', 'master_id' => '9zuVcerD7RjP.8_jFEATbD107IeWoF.z2BHv5Dx2LqX.G7'),
	'sidebar-top' => array('slave_id' => 'adoceansilnipetktop', 'master_id' => '9zuVcerD7RjP.8_jFEATbD107IeWoF.z2BHv5Dx2LqX.G7'),
	'bottom' => array('slave_id' => 'adoceansiynpfiqeiio', 'master_id' => '9zuVcerD7RjP.8_jFEATbD107IeWoF.z2BHv5Dx2LqX.G7'),
	'upper' => array('slave_id' => 'adoceansivogmlnomsj', 'master_id' => '9zuVcerD7RjP.8_jFEATbD107IeWoF.z2BHv5Dx2LqX.G7'),
	'background' => array('slave_id' => 'adoceansispnsokirce', 'master_id' => '9zuVcerD7RjP.8_jFEATbD107IeWoF.z2BHv5Dx2LqX.G7'),
	'floater' => array('slave_id' => 'adoceansispepfmppoq', 'master_id' => '9zuVcerD7RjP.8_jFEATbD107IeWoF.z2BHv5Dx2LqX.G7'),
),
'c:univerzum' => array(
	'banderola' => array('slave_id' => 'adoceansixhikmnjiff', 'master_id' => 'd1ngsYt8dx7PyxclFO8.30Efrlu3jBrS2Qr4Ce0Y6Mr.87'),
	'billboard' => array('slave_id' => 'adoceansirjghdinrvv', 'master_id' => 'd1ngsYt8dx7PyxclFO8.30Efrlu3jBrS2Qr4Ce0Y6Mr.87'),
	'sidebar-bottom' => array('slave_id' => 'adoceansipafjcisfdd', 'master_id' => 'd1ngsYt8dx7PyxclFO8.30Efrlu3jBrS2Qr4Ce0Y6Mr.87'),
	'sidebar-top' => array('slave_id' => 'adoceansimbmpfvlkcy', 'master_id' => 'd1ngsYt8dx7PyxclFO8.30Efrlu3jBrS2Qr4Ce0Y6Mr.87'),
	'bottom' => array('slave_id' => 'adoceansizbdgjsfpxt', 'master_id' => 'd1ngsYt8dx7PyxclFO8.30Efrlu3jBrS2Qr4Ce0Y6Mr.87'),
	'upper' => array('slave_id' => 'adoceansiwckmmpptwo', 'master_id' => 'd1ngsYt8dx7PyxclFO8.30Efrlu3jBrS2Qr4Ce0Y6Mr.87'),
	'background' => array('slave_id' => 'adoceansitdrspmjiqn', 'master_id' => 'd1ngsYt8dx7PyxclFO8.30Efrlu3jBrS2Qr4Ce0Y6Mr.87'),
	'floater' => array('slave_id' => 'adoceansipamfjjjuul', 'master_id' => 'd1ngsYt8dx7PyxclFO8.30Efrlu3jBrS2Qr4Ce0Y6Mr.87'),
),
'c:sport' => array(
	'banderola' => array('slave_id' => 'adoceansipoqnhxhnxz', 'master_id' => 'QlXxYNbRDEv1.yHHFZY4jpI3w6uvTdIrflymH_bAB3v.67'),
	'billboard' => array('slave_id' => 'adoceansimphelurrsu', 'master_id' => 'QlXxYNbRDEv1.yHHFZY4jpI3w6uvTdIrflymH_bAB3v.67'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiojcqhjoium', 'master_id' => 'QlXxYNbRDEv1.yHHFZY4jpI3w6uvTdIrflymH_bAB3v.67'),
	'sidebar-top' => array('slave_id' => 'adoceansilkjglwhneh', 'master_id' => 'QlXxYNbRDEv1.yHHFZY4jpI3w6uvTdIrflymH_bAB3v.67'),
	'bottom' => array('slave_id' => 'adoceansiykqmotrrsc', 'master_id' => 'QlXxYNbRDEv1.yHHFZY4jpI3w6uvTdIrflymH_bAB3v.67'),
	'upper' => array('slave_id' => 'adoceansivlhtbrlgib', 'master_id' => 'QlXxYNbRDEv1.yHHFZY4jpI3w6uvTdIrflymH_bAB3v.67'),
	'background' => array('slave_id' => 'adoceansismojfofldw', 'master_id' => 'QlXxYNbRDEv1.yHHFZY4jpI3w6uvTdIrflymH_bAB3v.67'),
	'floater' => array('slave_id' => 'adoceansizbksptmncf', 'master_id' => 'QlXxYNbRDEv1.yHHFZY4jpI3w6uvTdIrflymH_bAB3v.67'),
),
'c:sprosceno' => array(
	'banderola' => array('slave_id' => 'adoceansikeclptmnby', 'master_id' => 'pU_mJgA18oTEzRuMvY8CekTM36B9_S7NLJ6BbX4Mzy3.e7'),
	'billboard' => array('slave_id' => 'adoceansixejrcrgslt', 'master_id' => 'pU_mJgA18oTEzRuMvY8CekTM36B9_S7NLJ6BbX4Mzy3.e7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansinioiqtphpp', 'master_id' => 'pU_mJgA18oTEzRuMvY8CekTM36B9_S7NLJ6BbX4Mzy3.e7'),
	'sidebar-top' => array('slave_id' => 'adoceansikjfpdrjmvk', 'master_id' => 'pU_mJgA18oTEzRuMvY8CekTM36B9_S7NLJ6BbX4Mzy3.e7'),
	'bottom' => array('slave_id' => 'adoceansixjmfhodrff', 'master_id' => 'pU_mJgA18oTEzRuMvY8CekTM36B9_S7NLJ6BbX4Mzy3.e7'),
	'upper' => array('slave_id' => 'adoceansiukdmklnfze', 'master_id' => 'pU_mJgA18oTEzRuMvY8CekTM36B9_S7NLJ6BbX4Mzy3.e7'),
	'background' => array('slave_id' => 'adoceansirlksnihkjz', 'master_id' => 'pU_mJgA18oTEzRuMvY8CekTM36B9_S7NLJ6BbX4Mzy3.e7'),
	'floater' => array('slave_id' => 'adoceansivonicpflev', 'master_id' => 'pU_mJgA18oTEzRuMvY8CekTM36B9_S7NLJ6BbX4Mzy3.e7'),
),
'c:panorama' => array(
	'banderola' => array('slave_id' => 'adoceansivjdihqrnjx', 'master_id' => '1XqRRnCYbIx.n3w4EXS6fwyoU54_pXH3iG6mYib2idT.c7'),
	'billboard' => array('slave_id' => 'adoceansiskkoknlsts', 'master_id' => '1XqRRnCYbIx.n3w4EXS6fwyoU54_pXH3iG6mYib2idT.c7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansilaiiopnjtb', 'master_id' => '1XqRRnCYbIx.n3w4EXS6fwyoU54_pXH3iG6mYib2idT.c7'),
	'sidebar-top' => array('slave_id' => 'adoceansiyapobnhodw', 'master_id' => '1XqRRnCYbIx.n3w4EXS6fwyoU54_pXH3iG6mYib2idT.c7'),
	'bottom' => array('slave_id' => 'adoceansivbgffkrsyr', 'master_id' => '1XqRRnCYbIx.n3w4EXS6fwyoU54_pXH3iG6mYib2idT.c7'),
	'upper' => array('slave_id' => 'adoceansiscnlixkhhq', 'master_id' => '1XqRRnCYbIx.n3w4EXS6fwyoU54_pXH3iG6mYib2idT.c7'),
	'background' => array('slave_id' => 'adoceansipdesluemcl', 'master_id' => '1XqRRnCYbIx.n3w4EXS6fwyoU54_pXH3iG6mYib2idT.c7'),
	'floater' => array('slave_id' => 'adoceansilnpllurreb', 'master_id' => '1XqRRnCYbIx.n3w4EXS6fwyoU54_pXH3iG6mYib2idT.c7'),
),
'c:kolumna' => array(
	'banderola' => array('slave_id' => 'adoceansitonolpmjwb', 'master_id' => '1xwMG2u57dekgGQGutlgNVHfrhAPOhrwkS3L0NpTZr3.k7'),
	'billboard' => array('slave_id' => 'adoceansiqpefpmgocw', 'master_id' => '1xwMG2u57dekgGQGutlgNVHfrhAPOhrwkS3L0NpTZr3.k7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansikmeinnmsfs', 'master_id' => '1xwMG2u57dekgGQGutlgNVHfrhAPOhrwkS3L0NpTZr3.k7'),
	'sidebar-top' => array('slave_id' => 'adoceansixmloqkghor', 'master_id' => '1xwMG2u57dekgGQGutlgNVHfrhAPOhrwkS3L0NpTZr3.k7'),
	'bottom' => array('slave_id' => 'adoceansiuncfeiqlum', 'master_id' => '1xwMG2u57dekgGQGutlgNVHfrhAPOhrwkS3L0NpTZr3.k7'),
	'upper' => array('slave_id' => 'adoceansirojlhvjqth', 'master_id' => '1xwMG2u57dekgGQGutlgNVHfrhAPOhrwkS3L0NpTZr3.k7'),
	'background' => array('slave_id' => 'adoceansiopqrksdfng', 'master_id' => '1xwMG2u57dekgGQGutlgNVHfrhAPOhrwkS3L0NpTZr3.k7'),
	'floater' => array('slave_id' => 'adoceansiomifixhnfg', 'master_id' => '1xwMG2u57dekgGQGutlgNVHfrhAPOhrwkS3L0NpTZr3.k7'),
),
'c:za-delnicarje' => array(
	'banderola' => array('slave_id' => 'adoceansirdifqohfqf', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
	'billboard' => array('slave_id' => 'adoceansioepldmrjaa', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiqeijdkdnhi', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
	'sidebar-top' => array('slave_id' => 'adoceansinfppgxmrvd', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
	'bottom' => array('slave_id' => 'adoceansikgggkugglc', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
	'upper' => array('slave_id' => 'adoceansixgnmnrqkzx', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
	'background' => array('slave_id' => 'adoceansiuhetqokpus', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
	'preroll-video' => array('slave_id' => 'adoceansiriljemeuan', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
	'floater' => array('slave_id' => 'adoceansimbdmmwsidk', 'master_id' => '0d4wLK92J6xv9.JzOU0ftRiY3MkonLCTqKecQW4c3Tf.Q7'),
),
'c:gospodarstvo' => array(
	'background' => array('slave_id' => 'adoceansirfdljkikoj', 'master_id' => 'OzL6QOehQ4d5a4zBaoCrHAGCAMBHH6LhkzwAoHfyPCb.f7'),
	'billboard' => array('slave_id' => 'adoceansiogkrmxroce', 'master_id' => 'OzL6QOehQ4d5a4zBaoCrHAGCAMBHH6LhkzwAoHfyPCb.f7'),
	'banderola' => array('slave_id' => 'adoceansilhrhqultxz', 'master_id' => 'OzL6QOehQ4d5a4zBaoCrHAGCAMBHH6LhkzwAoHfyPCb.f7'),
	'bottom' => array('slave_id' => 'adoceansiufmmqmgnlk', 'master_id' => 'OzL6QOehQ4d5a4zBaoCrHAGCAMBHH6LhkzwAoHfyPCb.f7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansisojpojgqqa', 'master_id' => 'OzL6QOehQ4d5a4zBaoCrHAGCAMBHH6LhkzwAoHfyPCb.f7'),
	'sidebar-top' => array('slave_id' => 'adoceansippqfcxpuav', 'master_id' => 'OzL6QOehQ4d5a4zBaoCrHAGCAMBHH6LhkzwAoHfyPCb.f7'),
	'upper' => array('slave_id' => 'adoceansimaimfujjqu', 'master_id' => 'OzL6QOehQ4d5a4zBaoCrHAGCAMBHH6LhkzwAoHfyPCb.f7'),
	'floater' => array('slave_id' => 'adoceansivbnrllirod', 'master_id' => 'OzL6QOehQ4d5a4zBaoCrHAGCAMBHH6LhkzwAoHfyPCb.f7'),
),
'c:crna-kronika' => array(
	'banderola' => array('slave_id' => 'adoceansimjjshlmfye', 'master_id' => 'ORMFWAGS7TKystpW7I_jmk3JEL4B7kOR4LfQVaOBeib.17'),
	'billboard' => array('slave_id' => 'adoceansizjqiligkiz', 'master_id' => 'ORMFWAGS7TKystpW7I_jmk3JEL4B7kOR4LfQVaOBeib.17'),
	'sidebar-bottom' => array('slave_id' => 'adoceansizhrhmlllqn', 'master_id' => 'ORMFWAGS7TKystpW7I_jmk3JEL4B7kOR4LfQVaOBeib.17'),
	'sidebar-top' => array('slave_id' => 'adoceansiwiiopifqli', 'master_id' => 'ORMFWAGS7TKystpW7I_jmk3JEL4B7kOR4LfQVaOBeib.17'),
	'bottom' => array('slave_id' => 'adoceansitjpedwouvd', 'master_id' => 'ORMFWAGS7TKystpW7I_jmk3JEL4B7kOR4LfQVaOBeib.17'),
	'upper' => array('slave_id' => 'adoceansiqkglgtijac', 'master_id' => 'ORMFWAGS7TKystpW7I_jmk3JEL4B7kOR4LfQVaOBeib.17'),
	'background' => array('slave_id' => 'adoceansinlnrjqsnzx', 'master_id' => 'ORMFWAGS7TKystpW7I_jmk3JEL4B7kOR4LfQVaOBeib.17'),
	'floater' => array('slave_id' => 'adoceansirlroekoikl', 'master_id' => 'ORMFWAGS7TKystpW7I_jmk3JEL4B7kOR4LfQVaOBeib.17'),
),
'c:ljudje' => array(
	'banderola' => array('slave_id' => 'adoceansirajmgsepwt', 'master_id' => 'uP6s8JGRTTxXBoPZuKJgDeh.EL5YYEORv9I69aWzDYD.97'),
	'billboard' => array('slave_id' => 'adoceansiobqsjpotvo', 'master_id' => 'uP6s8JGRTTxXBoPZuKJgDeh.EL5YYEORv9I69aWzDYD.97'),
	'sidebar-bottom' => array('slave_id' => 'adoceansirhhgelssdj', 'master_id' => 'uP6s8JGRTTxXBoPZuKJgDeh.EL5YYEORv9I69aWzDYD.97'),
	'sidebar-top' => array('slave_id' => 'adoceansioiomhimhxi', 'master_id' => 'uP6s8JGRTTxXBoPZuKJgDeh.EL5YYEORv9I69aWzDYD.97'),
	'bottom' => array('slave_id' => 'adoceansiljftkvfmhd', 'master_id' => 'uP6s8JGRTTxXBoPZuKJgDeh.EL5YYEORv9I69aWzDYD.97'),
	'upper' => array('slave_id' => 'adoceansiyjmjospqgy', 'master_id' => 'uP6s8JGRTTxXBoPZuKJgDeh.EL5YYEORv9I69aWzDYD.97'),
	'background' => array('slave_id' => 'adoceansivkdqbqjfwx', 'master_id' => 'uP6s8JGRTTxXBoPZuKJgDeh.EL5YYEORv9I69aWzDYD.97'),
	'floater' => array('slave_id' => 'adoceansimecfgtfpjs', 'master_id' => 'uP6s8JGRTTxXBoPZuKJgDeh.EL5YYEORv9I69aWzDYD.97'),
),
'c:politika' => array(
	'banderola' => array('slave_id' => 'adoceansimgkjoojpes', 'master_id' => 'yjD8bsQkjYbO3V4GBUliJDzK8RCWgmdHy7INci7q_K..H7'),
	'billboard' => array('slave_id' => 'adoceansizgrpbmduon', 'master_id' => 'yjD8bsQkjYbO3V4GBUliJDzK8RCWgmdHy7INci7q_K..H7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansitpnggperkx', 'master_id' => 'yjD8bsQkjYbO3V4GBUliJDzK8RCWgmdHy7INci7q_K..H7'),
	'sidebar-top' => array('slave_id' => 'adoceansiqafnjmofpw', 'master_id' => 'yjD8bsQkjYbO3V4GBUliJDzK8RCWgmdHy7INci7q_K..H7'),
	'bottom' => array('slave_id' => 'adoceansinbmtmjikzr', 'master_id' => 'yjD8bsQkjYbO3V4GBUliJDzK8RCWgmdHy7INci7q_K..H7'),
	'upper' => array('slave_id' => 'adoceansikcdkqwrojm', 'master_id' => 'yjD8bsQkjYbO3V4GBUliJDzK8RCWgmdHy7INci7q_K..H7'),
	'background' => array('slave_id' => 'adoceansixckqdultth', 'master_id' => 'yjD8bsQkjYbO3V4GBUliJDzK8RCWgmdHy7INci7q_K..H7'),
	'floater' => array('slave_id' => 'adoceansiwfqrmnjirm', 'master_id' => 'yjD8bsQkjYbO3V4GBUliJDzK8RCWgmdHy7INci7q_K..H7'),
),
'c:okolje' => array(
	'banderola' => array('slave_id' => 'adoceansirnjtmvrifl', 'master_id' => 'Yyb6VcoNQ4CrXIgZ3dN1379O.IJJhfA_0M9JmNf7v93.c7'),
	'billboard' => array('slave_id' => 'adoceansiooqjqslnag', 'master_id' => 'Yyb6VcoNQ4CrXIgZ3dN1379O.IJJhfA_0M9JmNf7v93.c7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansislkgfndkrs', 'master_id' => 'Yyb6VcoNQ4CrXIgZ3dN1379O.IJJhfA_0M9JmNf7v93.c7'),
	'sidebar-top' => array('slave_id' => 'adoceansipmrmiknoqn', 'master_id' => 'Yyb6VcoNQ4CrXIgZ3dN1379O.IJJhfA_0M9JmNf7v93.c7'),
	'bottom' => array('slave_id' => 'adoceansimnitlxgtai', 'master_id' => 'Yyb6VcoNQ4CrXIgZ3dN1379O.IJJhfA_0M9JmNf7v93.c7'),
	'upper' => array('slave_id' => 'adoceansiznpjpuqhjh', 'master_id' => 'Yyb6VcoNQ4CrXIgZ3dN1379O.IJJhfA_0M9JmNf7v93.c7'),
	'background' => array('slave_id' => 'adoceansiwogqcskmpc', 'master_id' => 'Yyb6VcoNQ4CrXIgZ3dN1379O.IJJhfA_0M9JmNf7v93.c7'),
	'floater' => array('slave_id' => 'adoceansizejljqptxn', 'master_id' => 'Yyb6VcoNQ4CrXIgZ3dN1379O.IJJhfA_0M9JmNf7v93.c7'),
),
'c:zdravje' => array(
	'banderola' => array('slave_id' => 'adoceansimdlqesgjuk', 'master_id' => 'pb5W1gC7QnBf6jCc547iDG.P0qWvLT6l_Q59A3g34hv.67'),
	'billboard' => array('slave_id' => 'adoceansiwejnlmksoa', 'master_id' => 'pb5W1gC7QnBf6jCc547iDG.P0qWvLT6l_Q59A3g34hv.67'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiwlhhjvhgfu', 'master_id' => 'pb5W1gC7QnBf6jCc547iDG.P0qWvLT6l_Q59A3g34hv.67'),
	'sidebar-top' => array('slave_id' => 'adoceansitmonmsrkep', 'master_id' => 'pb5W1gC7QnBf6jCc547iDG.P0qWvLT6l_Q59A3g34hv.67'),
	'bottom' => array('slave_id' => 'adoceansiqnfeqplpkk', 'master_id' => 'pb5W1gC7QnBf6jCc547iDG.P0qWvLT6l_Q59A3g34hv.67'),
	'upper' => array('slave_id' => 'adoceansinomkdnfuff', 'master_id' => 'pb5W1gC7QnBf6jCc547iDG.P0qWvLT6l_Q59A3g34hv.67'),
	'background' => array('slave_id' => 'adoceansikpdrgkpize', 'master_id' => 'pb5W1gC7QnBf6jCc547iDG.P0qWvLT6l_Q59A3g34hv.67'),
	'floater' => array('slave_id' => 'adoceansiniffhvggmb', 'master_id' => 'pb5W1gC7QnBf6jCc547iDG.P0qWvLT6l_Q59A3g34hv.67'),
),
'c:znanost-in-tehnologija' => array(
	'banderola' => array('slave_id' => 'adoceansirkkkdjpshz', 'master_id' => '2H6cud6W7aCbaM7cV1hZ8YBxY6ZP7BJTfJ2G.vCbOb3.Q7'),
	'billboard' => array('slave_id' => 'adoceansiolrqgwihqy', 'master_id' => '2H6cud6W7aCbaM7cV1hZ8YBxY6ZP7BJTfJ2G.vCbOb3.Q7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansixpkhkxinyz', 'master_id' => '2H6cud6W7aCbaM7cV1hZ8YBxY6ZP7BJTfJ2G.vCbOb3.Q7'),
	'sidebar-top' => array('slave_id' => 'adoceansiuaconusrtu', 'master_id' => '2H6cud6W7aCbaM7cV1hZ8YBxY6ZP7BJTfJ2G.vCbOb3.Q7'),
	'bottom' => array('slave_id' => 'adoceansirbjebsmgjt', 'master_id' => '2H6cud6W7aCbaM7cV1hZ8YBxY6ZP7BJTfJ2G.vCbOb3.Q7'),
	'upper' => array('slave_id' => 'adoceansiocqkepglto', 'master_id' => '2H6cud6W7aCbaM7cV1hZ8YBxY6ZP7BJTfJ2G.vCbOb3.Q7'),
	'background' => array('slave_id' => 'adoceansildhrhmqpdj', 'master_id' => '2H6cud6W7aCbaM7cV1hZ8YBxY6ZP7BJTfJ2G.vCbOb3.Q7'),
	'floater' => array('slave_id' => 'adoceansikjmlksqklw', 'master_id' => '2H6cud6W7aCbaM7cV1hZ8YBxY6ZP7BJTfJ2G.vCbOb3.Q7'),
),
'c:intimno' => array(
	'banderola' => array('slave_id' => 'adoceansiwbkecqhmps', 'master_id' => '.R.1pWNYjRvA69pNL8ZTG01BE4Jm..Is3scGauDk6Rz.i7'),
	'billboard' => array('slave_id' => 'adoceansiqdiriklftm', 'master_id' => '.R.1pWNYjRvA69pNL8ZTG01BE4Jm..Is3scGauDk6Rz.i7'),
	'background' => array('slave_id' => 'adoceansiugelgpshcw', 'master_id' => '.R.1pWNYjRvA69pNL8ZTG01BE4Jm..Is3scGauDk6Rz.i7'),
	'bottom' => array('slave_id' => 'adoceansiohkjhxjgae', 'master_id' => '.R.1pWNYjRvA69pNL8ZTG01BE4Jm..Is3scGauDk6Rz.i7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansizapsirdopp', 'master_id' => '.R.1pWNYjRvA69pNL8ZTG01BE4Jm..Is3scGauDk6Rz.i7'),
	'sidebar-top' => array('slave_id' => 'adoceansiwbgjmonskk', 'master_id' => '.R.1pWNYjRvA69pNL8ZTG01BE4Jm..Is3scGauDk6Rz.i7'),
	'upper' => array('slave_id' => 'adoceansitcnpplhhej', 'master_id' => '.R.1pWNYjRvA69pNL8ZTG01BE4Jm..Is3scGauDk6Rz.i7'),
	'floater' => array('slave_id' => 'adoceansisceipisftc', 'master_id' => '.R.1pWNYjRvA69pNL8ZTG01BE4Jm..Is3scGauDk6Rz.i7'),
),
'c:kulinarika-in-potovanja' => array(
	'banderola' => array('slave_id' => 'adoceansiyjqeeujklg', 'master_id' => 'U07nLgnJd6hWheaRx2EO6GAzwxavhtJNDKPPplCJsqD.w7'),
	'billboard' => array('slave_id' => 'adoceansivkhlhrdpgb', 'master_id' => 'U07nLgnJd6hWheaRx2EO6GAzwxavhtJNDKPPplCJsqD.w7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiqdegdjrlke', 'master_id' => 'U07nLgnJd6hWheaRx2EO6GAzwxavhtJNDKPPplCJsqD.w7'),
	'sidebar-top' => array('slave_id' => 'adoceansinelmgwkqjz', 'master_id' => 'U07nLgnJd6hWheaRx2EO6GAzwxavhtJNDKPPplCJsqD.w7'),
	'bottom' => array('slave_id' => 'adoceansikfctjtefoy', 'master_id' => 'U07nLgnJd6hWheaRx2EO6GAzwxavhtJNDKPPplCJsqD.w7'),
	'upper' => array('slave_id' => 'adoceansixfjjnqojnt', 'master_id' => 'U07nLgnJd6hWheaRx2EO6GAzwxavhtJNDKPPplCJsqD.w7'),
	'background' => array('slave_id' => 'adoceansiugqpqnioxo', 'master_id' => 'U07nLgnJd6hWheaRx2EO6GAzwxavhtJNDKPPplCJsqD.w7'),
	'floater' => array('slave_id' => 'adoceansipdlocwlkdx', 'master_id' => 'U07nLgnJd6hWheaRx2EO6GAzwxavhtJNDKPPplCJsqD.w7'),
),
'c:pozitivno-in-aktivno' => array(
	'banderola' => array('slave_id' => 'adoceansiwoklitegjk', 'master_id' => 'RNhap7zWUy93Mdf6g8wVBn6I4VKh2sbnhtBqm5Stqsz.D7'),
	'billboard' => array('slave_id' => 'adoceansitprrlqokif', 'master_id' => 'RNhap7zWUy93Mdf6g8wVBn6I4VKh2sbnhtBqm5Stqsz.D7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiudrghrfiyg', 'master_id' => 'RNhap7zWUy93Mdf6g8wVBn6I4VKh2sbnhtBqm5Stqsz.D7'),
	'sidebar-top' => array('slave_id' => 'adoceansireinkopmib', 'master_id' => 'RNhap7zWUy93Mdf6g8wVBn6I4VKh2sbnhtBqm5Stqsz.D7'),
	'bottom' => array('slave_id' => 'adoceansiofptnljrsw', 'master_id' => 'RNhap7zWUy93Mdf6g8wVBn6I4VKh2sbnhtBqm5Stqsz.D7'),
	'upper' => array('slave_id' => 'adoceansilggkbjdgtv', 'master_id' => 'RNhap7zWUy93Mdf6g8wVBn6I4VKh2sbnhtBqm5Stqsz.D7'),
	'background' => array('slave_id' => 'adoceansiygnqewmkwq', 'master_id' => 'RNhap7zWUy93Mdf6g8wVBn6I4VKh2sbnhtBqm5Stqsz.D7'),
	'floater' => array('slave_id' => 'adoceansitghiqkdnxh', 'master_id' => 'RNhap7zWUy93Mdf6g8wVBn6I4VKh2sbnhtBqm5Stqsz.D7'),
),
'c:zanimivosti' => array(
	'banderola' => array('slave_id' => 'adoceansiofdpdndlie', 'master_id' => 'S3Rc6dcenczvUkln0k6mdi4MUe8xmyd21nZ6P2RHSmH.O7'),
	'billboard' => array('slave_id' => 'adoceansiygrlkxgugu', 'master_id' => 'S3Rc6dcenczvUkln0k6mdi4MUe8xmyd21nZ6P2RHSmH.O7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansivhehitgpcl', 'master_id' => 'S3Rc6dcenczvUkln0k6mdi4MUe8xmyd21nZ6P2RHSmH.O7'),
	'sidebar-top' => array('slave_id' => 'adoceansisilnlqqtbg', 'master_id' => 'S3Rc6dcenczvUkln0k6mdi4MUe8xmyd21nZ6P2RHSmH.O7'),
	'bottom' => array('slave_id' => 'adoceansipjcepnkirf', 'master_id' => 'S3Rc6dcenczvUkln0k6mdi4MUe8xmyd21nZ6P2RHSmH.O7'),
	'upper' => array('slave_id' => 'adoceansimkjkclenma', 'master_id' => 'S3Rc6dcenczvUkln0k6mdi4MUe8xmyd21nZ6P2RHSmH.O7'),
	'background' => array('slave_id' => 'adoceansizkqqfiorav', 'master_id' => 'S3Rc6dcenczvUkln0k6mdi4MUe8xmyd21nZ6P2RHSmH.O7'),
	'floater' => array('slave_id' => 'adoceansiqhoodinrhc', 'master_id' => 'S3Rc6dcenczvUkln0k6mdi4MUe8xmyd21nZ6P2RHSmH.O7'),
),
'c:zvezde' => array(
	'banderola' => array('slave_id' => 'adoceansitmcjculukt', 'master_id' => 'S71G1teh4g2UXSX.NJLGgOWzbXpdKGcNHNMVGl3GIpH.W7'),
	'billboard' => array('slave_id' => 'adoceansiqnjpfrfjes', 'master_id' => 'S71G1teh4g2UXSX.NJLGgOWzbXpdKGcNHNMVGl3GIpH.W7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiydohljkune', 'master_id' => 'S71G1teh4g2UXSX.NJLGgOWzbXpdKGcNHNMVGl3GIpH.W7'),
	'sidebar-top' => array('slave_id' => 'adoceansivefoowdjhd', 'master_id' => 'S71G1teh4g2UXSX.NJLGgOWzbXpdKGcNHNMVGl3GIpH.W7'),
	'bottom' => array('slave_id' => 'adoceansisfmecunncy', 'master_id' => 'S71G1teh4g2UXSX.NJLGgOWzbXpdKGcNHNMVGl3GIpH.W7'),
	'upper' => array('slave_id' => 'adoceansipgdlfrhsxt', 'master_id' => 'S71G1teh4g2UXSX.NJLGgOWzbXpdKGcNHNMVGl3GIpH.W7'),
	'background' => array('slave_id' => 'adoceansimhkriorggs', 'master_id' => 'S71G1teh4g2UXSX.NJLGgOWzbXpdKGcNHNMVGl3GIpH.W7'),
	'floater' => array('slave_id' => 'adoceansixjdsnpkpvr', 'master_id' => 'S71G1teh4g2UXSX.NJLGgOWzbXpdKGcNHNMVGl3GIpH.W7'),
),
's:slovenija/crna-kronika' => array(
	'sidebar-top' => array('slave_id' => 'adoceansivjmnivkrat', 'master_id' => 'tjsGGDLNkho6dAAYm7v4RMvrXuWeC.tf6Bx4C9bW6mr.j7'),
	'single-bottom' => array('slave_id' => 'adoceansiracshxnsnp', 'master_id' => 'tjsGGDLNkho6dAAYm7v4RMvrXuWeC.tf6Bx4C9bW6mr.j7'),
	'banderola' => array('slave_id' => 'adoceansipocoeqnmfn', 'master_id' => 'tjsGGDLNkho6dAAYm7v4RMvrXuWeC.tf6Bx4C9bW6mr.j7'),
	'single-comment' => array('slave_id' => 'adoceansiocjsqjjkcg', 'master_id' => 'tjsGGDLNkho6dAAYm7v4RMvrXuWeC.tf6Bx4C9bW6mr.j7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansildqiexsomb', 'master_id' => 'tjsGGDLNkho6dAAYm7v4RMvrXuWeC.tf6Bx4C9bW6mr.j7'),
	'billboard' => array('slave_id' => 'adoceansiydhphumtww', 'master_id' => 'tjsGGDLNkho6dAAYm7v4RMvrXuWeC.tf6Bx4C9bW6mr.j7'),
	'floater' => array('slave_id' => 'adoceansixgejethjwj', 'master_id' => 'tjsGGDLNkho6dAAYm7v4RMvrXuWeC.tf6Bx4C9bW6mr.j7'),
),
's:slovenija/gospodarstvo' => array(
	'sidebar-top' => array('slave_id' => 'adoceansitlhldidhkp', 'master_id' => 'xUiR0IBBbDb5nbGbX3oLhBei4UJQWMbnpBgteLB2qFv.m7'),
	'single-bottom' => array('slave_id' => 'adoceansiqmorgvmlyk', 'master_id' => 'xUiR0IBBbDb5nbGbX3oLhBei4UJQWMbnpBgteLB2qFv.m7'),
	'banderola' => array('slave_id' => 'adoceansiylnkkiqovy', 'master_id' => 'xUiR0IBBbDb5nbGbX3oLhBei4UJQWMbnpBgteLB2qFv.m7'),
	'single-comment' => array('slave_id' => 'adoceansimkcsovgmks', 'master_id' => 'xUiR0IBBbDb5nbGbX3oLhBei4UJQWMbnpBgteLB2qFv.m7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansizkjictqqun', 'master_id' => 'xUiR0IBBbDb5nbGbX3oLhBei4UJQWMbnpBgteLB2qFv.m7'),
	'billboard' => array('slave_id' => 'adoceansiwlqofqkfom', 'master_id' => 'xUiR0IBBbDb5nbGbX3oLhBei4UJQWMbnpBgteLB2qFv.m7'),
	'floater' => array('slave_id' => 'adoceansiqepfklklxu', 'master_id' => 'xUiR0IBBbDb5nbGbX3oLhBei4UJQWMbnpBgteLB2qFv.m7'),
),
's:slovenija/ljudje' => array(
	'sidebar-top' => array('slave_id' => 'adoceansinnfiksgqef', 'master_id' => 'vEOcx4AV7Zlw1Ak3DmQsFlzwYBRmvmL0m4kDMN859i7..7'),
	'single-bottom' => array('slave_id' => 'adoceansikomonpquda', 'master_id' => 'vEOcx4AV7Zlw1Ak3DmQsFlzwYBRmvmL0m4kDMN859i7..7'),
	'banderola' => array('slave_id' => 'adoceansivmernvjtft', 'master_id' => 'vEOcx4AV7Zlw1Ak3DmQsFlzwYBRmvmL0m4kDMN859i7..7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansitmhfjnekuh', 'master_id' => 'vEOcx4AV7Zlw1Ak3DmQsFlzwYBRmvmL0m4kDMN859i7..7'),
	'single-comment' => array('slave_id' => 'adoceansiqnolmkootc', 'master_id' => 'vEOcx4AV7Zlw1Ak3DmQsFlzwYBRmvmL0m4kDMN859i7..7'),
	'billboard' => array('slave_id' => 'adoceansinofspxhtdx', 'master_id' => 'vEOcx4AV7Zlw1Ak3DmQsFlzwYBRmvmL0m4kDMN859i7..7'),
	'floater' => array('slave_id' => 'adoceansinfgmnieqsp', 'master_id' => 'vEOcx4AV7Zlw1Ak3DmQsFlzwYBRmvmL0m4kDMN859i7..7'),
),
's:slovenija/politika' => array(
	'sidebar-top' => array('slave_id' => 'adoceansixodfbnkjtz', 'master_id' => 'N5c2DysdgslloQU1v7iPBRiGnNco1TBXL03c0NUUfZX.o7'),
	'single-bottom' => array('slave_id' => 'adoceansiupklekeodu', 'master_id' => 'N5c2DysdgslloQU1v7iPBRiGnNco1TBXL03c0NUUfZX.o7'),
	'banderola' => array('slave_id' => 'adoceansisnlhbtdivs', 'master_id' => 'N5c2DysdgslloQU1v7iPBRiGnNco1TBXL03c0NUUfZX.o7'),
	'single-comment' => array('slave_id' => 'adoceansikpmidvrhiw', 'master_id' => 'N5c2DysdgslloQU1v7iPBRiGnNco1TBXL03c0NUUfZX.o7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansixpdpgslmsr', 'master_id' => 'N5c2DysdgslloQU1v7iPBRiGnNco1TBXL03c0NUUfZX.o7'),
	'billboard' => array('slave_id' => 'adoceansirbcmnmpfsl', 'master_id' => 'N5c2DysdgslloQU1v7iPBRiGnNco1TBXL03c0NUUfZX.o7'),
	'floater' => array('slave_id' => 'adoceansikgnsqvnugk', 'master_id' => 'N5c2DysdgslloQU1v7iPBRiGnNco1TBXL03c0NUUfZX.o7'),
),
's:svet' => array(
	'sidebar-top' => array('slave_id' => 'adoceansinkgpqvdkjx', 'master_id' => 'o2bsiyn7LaG7f04EvW28gGzabYU24WbP6OHIBFyBXCj.v7'),
	'single-bottom' => array('slave_id' => 'adoceansiklnfetnoes', 'master_id' => 'o2bsiyn7LaG7f04EvW28gGzabYU24WbP6OHIBFyBXCj.v7'),
	'banderola' => array('slave_id' => 'adoceansindnejpiior', 'master_id' => 'o2bsiyn7LaG7f04EvW28gGzabYU24WbP6OHIBFyBXCj.v7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansizelgpjluqt', 'master_id' => 'o2bsiyn7LaG7f04EvW28gGzabYU24WbP6OHIBFyBXCj.v7'),
	'single-comment' => array('slave_id' => 'adoceansiwfcncxejvs', 'master_id' => 'o2bsiyn7LaG7f04EvW28gGzabYU24WbP6OHIBFyBXCj.v7'),
	'billboard' => array('slave_id' => 'adoceansitgjtfuonun', 'master_id' => 'o2bsiyn7LaG7f04EvW28gGzabYU24WbP6OHIBFyBXCj.v7'),
	'floater' => array('slave_id' => 'adoceansivlopissuoj', 'master_id' => 'o2bsiyn7LaG7f04EvW28gGzabYU24WbP6OHIBFyBXCj.v7'),
),
's:univerzum/okolje' => array(
	'sidebar-top' => array('slave_id' => 'adoceansixlemhqhton', 'master_id' => 'FA9QCk1r54JShWJw9vd5d_Sajy.COQ8kf0QEzaI5OwP.h7'),
	'single-bottom' => array('slave_id' => 'adoceansiumlsknrhxm', 'master_id' => 'FA9QCk1r54JShWJw9vd5d_Sajy.COQ8kf0QEzaI5OwP.h7'),
	'banderola' => array('slave_id' => 'adoceansikeelmmsmym', 'master_id' => 'FA9QCk1r54JShWJw9vd5d_Sajy.COQ8kf0QEzaI5OwP.h7'),
	'single-comment' => array('slave_id' => 'adoceansiqhqjjrispi', 'master_id' => 'FA9QCk1r54JShWJw9vd5d_Sajy.COQ8kf0QEzaI5OwP.h7'),
	'billboard' => array('slave_id' => 'adoceansinihqmosgjh', 'master_id' => 'FA9QCk1r54JShWJw9vd5d_Sajy.COQ8kf0QEzaI5OwP.h7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansikjogqlmlec', 'master_id' => 'FA9QCk1r54JShWJw9vd5d_Sajy.COQ8kf0QEzaI5OwP.h7'),
	'floater' => array('slave_id' => 'adoceansismfgmpmjei', 'master_id' => 'FA9QCk1r54JShWJw9vd5d_Sajy.COQ8kf0QEzaI5OwP.h7'),
),
's:univerzum/zdravje' => array(
	'sidebar-top' => array('slave_id' => 'adoceansioojpbifryc', 'master_id' => 'gHhKXhyD8yTE1sO5KIE13MdIcsYwhn6w_usw74sys8f.P7'),
	'single-bottom' => array('slave_id' => 'adoceansilpqffvofhb', 'master_id' => 'gHhKXhyD8yTE1sO5KIE13MdIcsYwhn6w_usw74sys8f.P7'),
	'banderola' => array('slave_id' => 'adoceansixelrpjmrxh', 'master_id' => 'gHhKXhyD8yTE1sO5KIE13MdIcsYwhn6w_usw74sys8f.P7'),
	'billboard' => array('slave_id' => 'adoceansixjfndjgqzx', 'master_id' => 'gHhKXhyD8yTE1sO5KIE13MdIcsYwhn6w_usw74sys8f.P7'),
	'single-comment' => array('slave_id' => 'adoceansiukmtgwpuns', 'master_id' => 'gHhKXhyD8yTE1sO5KIE13MdIcsYwhn6w_usw74sys8f.P7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansirldkktjjdr', 'master_id' => 'gHhKXhyD8yTE1sO5KIE13MdIcsYwhn6w_usw74sys8f.P7'),
	'floater' => array('slave_id' => 'adoceansimodtckqsjy', 'master_id' => 'gHhKXhyD8yTE1sO5KIE13MdIcsYwhn6w_usw74sys8f.P7'),
),
's:univerzum/znanost-in-tehnologija' => array(
	'sidebar-top' => array('slave_id' => 'adoceansiyphmisikrw', 'master_id' => 'fX035cOUJz5xI9DvhKGI0HTDo10d75HaX00GoecKyXj.l7'),
	'single-bottom' => array('slave_id' => 'adoceansivapslpsobr', 'master_id' => 'fX035cOUJz5xI9DvhKGI0HTDo10d75HaX00GoecKyXj.l7'),
	'banderola' => array('slave_id' => 'adoceansiufcidxfgng', 'master_id' => 'fX035cOUJz5xI9DvhKGI0HTDo10d75HaX00GoecKyXj.l7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiomkqnqdonm', 'master_id' => 'fX035cOUJz5xI9DvhKGI0HTDo10d75HaX00GoecKyXj.l7'),
	'billboard' => array('slave_id' => 'adoceansilnrgbonsih', 'master_id' => 'fX035cOUJz5xI9DvhKGI0HTDo10d75HaX00GoecKyXj.l7'),
	'single-comment' => array('slave_id' => 'adoceansiyninelhhcg', 'master_id' => 'fX035cOUJz5xI9DvhKGI0HTDo10d75HaX00GoecKyXj.l7'),
	'floater' => array('slave_id' => 'adoceansizokjgxjhsx', 'master_id' => 'fX035cOUJz5xI9DvhKGI0HTDo10d75HaX00GoecKyXj.l7'),
),
's:sport' => array(
	'sidebar-top' => array('slave_id' => 'adoceansimdeggxpmwg', 'master_id' => '3SbhYKNIrJCwOGcWpeuev2_dXnqpcfs9lsSYJON7iAP.t7'),
	'single-bottom' => array('slave_id' => 'adoceansizdlmjujrvb', 'master_id' => '3SbhYKNIrJCwOGcWpeuev2_dXnqpcfs9lsSYJON7iAP.t7'),
	'banderola' => array('slave_id' => 'adoceansiohqekrjphw', 'master_id' => '3SbhYKNIrJCwOGcWpeuev2_dXnqpcfs9lsSYJON7iAP.t7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansimbfhcqojhq', 'master_id' => '3SbhYKNIrJCwOGcWpeuev2_dXnqpcfs9lsSYJON7iAP.t7'),
	'billboard' => array('slave_id' => 'adoceansizbmnfniogl', 'master_id' => '3SbhYKNIrJCwOGcWpeuev2_dXnqpcfs9lsSYJON7iAP.t7'),
	'single-comment' => array('slave_id' => 'adoceansiwcdejkssbg', 'master_id' => '3SbhYKNIrJCwOGcWpeuev2_dXnqpcfs9lsSYJON7iAP.t7'),
	'floater' => array('slave_id' => 'adoceansitajgnrnqin', 'master_id' => '3SbhYKNIrJCwOGcWpeuev2_dXnqpcfs9lsSYJON7iAP.t7'),
),
's:sprosceno/intimno' => array(
	'sidebar-top' => array('slave_id' => 'adoceansiobjiluhhso', 'master_id' => 'fTBMncMmPckQy_PrVV2AE38pnIypazB1qV..9oE2rt3.v7'),
	'single-bottom' => array('slave_id' => 'adoceansilcqoorrlrj', 'master_id' => 'fTBMncMmPckQy_PrVV2AE38pnIypazB1qV..9oE2rt3.v7'),
	'banderola' => array('slave_id' => 'adoceansimpjeinhrai', 'master_id' => 'fTBMncMmPckQy_PrVV2AE38pnIypazB1qV..9oE2rt3.v7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiveoflrgibv', 'master_id' => 'fTBMncMmPckQy_PrVV2AE38pnIypazB1qV..9oE2rt3.v7'),
	'single-comment' => array('slave_id' => 'adoceansisffmooqmlq', 'master_id' => 'fTBMncMmPckQy_PrVV2AE38pnIypazB1qV..9oE2rt3.v7'),
	'billboard' => array('slave_id' => 'adoceansipgmsbmkrgl', 'master_id' => 'fTBMncMmPckQy_PrVV2AE38pnIypazB1qV..9oE2rt3.v7'),
	'floater' => array('slave_id' => 'adoceansiuhlphqrnve', 'master_id' => 'fTBMncMmPckQy_PrVV2AE38pnIypazB1qV..9oE2rt3.v7'),
),
's:sporsceno/kulinarika-in-potovanja' => array(
	'sidebar-top' => array('slave_id' => 'adoceansiychfcplqxe', 'master_id' => 'UkYFN5bu7V31TABnxTB2O9XdAZ9llQdnpwW9DamelmX.Y7'),
	'single-bottom' => array('slave_id' => 'adoceansivdolfmffrd', 'master_id' => 'UkYFN5bu7V31TABnxTB2O9XdAZ9llQdnpwW9DamelmX.Y7'),
	'banderola' => array('slave_id' => 'adoceansizpqklkrfyh', 'master_id' => 'UkYFN5bu7V31TABnxTB2O9XdAZ9llQdnpwW9DamelmX.Y7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansimhdjfjegwk', 'master_id' => 'UkYFN5bu7V31TABnxTB2O9XdAZ9llQdnpwW9DamelmX.Y7'),
	'single-comment' => array('slave_id' => 'adoceansizhkpiwnkzf', 'master_id' => 'UkYFN5bu7V31TABnxTB2O9XdAZ9llQdnpwW9DamelmX.Y7'),
	'billboard' => array('slave_id' => 'adoceansitjimpqrtev', 'master_id' => 'UkYFN5bu7V31TABnxTB2O9XdAZ9llQdnpwW9DamelmX.Y7'),
	'floater' => array('slave_id' => 'adoceansiricglnlsbz', 'master_id' => 'UkYFN5bu7V31TABnxTB2O9XdAZ9llQdnpwW9DamelmX.Y7'),
),
's:sprosceno/pozitivno-in-aktivno' => array(
	'sidebar-top' => array('slave_id' => 'adoceansisefsijpjby', 'master_id' => 'qHz8FG6ejRxVon7rnLifTdix4QKI.8eXlWaKggBSPFX.d7'),
	'single-bottom' => array('slave_id' => 'adoceansipfmimwiolt', 'master_id' => 'qHz8FG6ejRxVon7rnLifTdix4QKI.8eXlWaKggBSPFX.d7'),
	'banderola' => array('slave_id' => 'adoceansiwairoxkktc', 'master_id' => 'qHz8FG6ejRxVon7rnLifTdix4QKI.8eXlWaKggBSPFX.d7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansinlgjglfnpp', 'master_id' => 'qHz8FG6ejRxVon7rnLifTdix4QKI.8eXlWaKggBSPFX.d7'),
	'single-comment' => array('slave_id' => 'adoceansikmnpjiprok', 'master_id' => 'qHz8FG6ejRxVon7rnLifTdix4QKI.8eXlWaKggBSPFX.d7'),
	'billboard' => array('slave_id' => 'adoceansixmegnvigij', 'master_id' => 'qHz8FG6ejRxVon7rnLifTdix4QKI.8eXlWaKggBSPFX.d7'),
	'floater' => array('slave_id' => 'adoceansiojjmokfhvy', 'master_id' => 'qHz8FG6ejRxVon7rnLifTdix4QKI.8eXlWaKggBSPFX.d7'),
),
's:sprosceno/zanimivosti' => array(
	'sidebar-top' => array('slave_id' => 'adoceansimgdpptssvo', 'master_id' => 'KH2hq95JzMdLJOdHLQWOWEhsbXnIqWcNUogys3L5hMv.K7'),
	'single-bottom' => array('slave_id' => 'adoceansizgkfdrmhan', 'master_id' => 'KH2hq95JzMdLJOdHLQWOWEhsbXnIqWcNUogys3L5hMv.K7'),
	'banderola' => array('slave_id' => 'adoceansitbphcvepzx', 'master_id' => 'KH2hq95JzMdLJOdHLQWOWEhsbXnIqWcNUogys3L5hMv.K7'),
	'single-comment' => array('slave_id' => 'adoceansiroctdqmpnz', 'master_id' => 'KH2hq95JzMdLJOdHLQWOWEhsbXnIqWcNUogys3L5hMv.K7'),
	'billboard' => array('slave_id' => 'adoceansiopjjhnguiu', 'master_id' => 'KH2hq95JzMdLJOdHLQWOWEhsbXnIqWcNUogys3L5hMv.K7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiyaigoxjnmo', 'master_id' => 'KH2hq95JzMdLJOdHLQWOWEhsbXnIqWcNUogys3L5hMv.K7'),
	'floater' => array('slave_id' => 'adoceansilkqsbiplft', 'master_id' => 'KH2hq95JzMdLJOdHLQWOWEhsbXnIqWcNUogys3L5hMv.K7'),
),
's:sprosceno/zvezde' => array(
	'sidebar-top' => array('slave_id' => 'adoceansitiisjlqqud', 'master_id' => 'kW5WoU8oQf5E1cWLj655.hkSrokA1xtDUg8IlxJRWoL.y7'),
	'single-bottom' => array('slave_id' => 'adoceansiqjpinikfzc', 'master_id' => 'kW5WoU8oQf5E1cWLj655.hkSrokA1xtDUg8IlxJRWoL.y7'),
	'banderola' => array('slave_id' => 'adoceansiqcgofsotjs', 'master_id' => 'kW5WoU8oQf5E1cWLj655.hkSrokA1xtDUg8IlxJRWoL.y7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiscgtesngbi', 'master_id' => 'kW5WoU8oQf5E1cWLj655.hkSrokA1xtDUg8IlxJRWoL.y7'),
	'billboard' => array('slave_id' => 'adoceansipdnjiphlwd', 'master_id' => 'kW5WoU8oQf5E1cWLj655.hkSrokA1xtDUg8IlxJRWoL.y7'),
	'single-comment' => array('slave_id' => 'adoceansimeeqlmrpgy', 'master_id' => 'kW5WoU8oQf5E1cWLj655.hkSrokA1xtDUg8IlxJRWoL.y7'),
	'floater' => array('slave_id' => 'adoceansiykhjfviqpo', 'master_id' => 'kW5WoU8oQf5E1cWLj655.hkSrokA1xtDUg8IlxJRWoL.y7'),
),
's:panorama' => array(
	'sidebar-top' => array('slave_id' => 'adoceansizjjomnpnzv', 'master_id' => 'WxYHkpeiN30.BlrO_J6UJvzQ7432bc9vVc5RsX573TX.l7'),
	'single-bottom' => array('slave_id' => 'adoceansiwkqeqkjsuq', 'master_id' => 'WxYHkpeiN30.BlrO_J6UJvzQ7432bc9vVc5RsX573TX.l7'),
	'banderola' => array('slave_id' => 'adoceansillgehlgkhd', 'master_id' => 'WxYHkpeiN30.BlrO_J6UJvzQ7432bc9vVc5RsX573TX.l7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiljokhqilbv', 'master_id' => 'WxYHkpeiN30.BlrO_J6UJvzQ7432bc9vVc5RsX573TX.l7'),
	'single-comment' => array('slave_id' => 'adoceansiyjfrknspaq', 'master_id' => 'WxYHkpeiN30.BlrO_J6UJvzQ7432bc9vVc5RsX573TX.l7'),
	'billboard' => array('slave_id' => 'adoceansivkmhokmuvl', 'master_id' => 'WxYHkpeiN30.BlrO_J6UJvzQ7432bc9vVc5RsX573TX.l7'),
	'floater' => array('slave_id' => 'adoceansitdipgoqgcz', 'master_id' => 'WxYHkpeiN30.BlrO_J6UJvzQ7432bc9vVc5RsX573TX.l7'),
),
's:kolumna' => array(
	'sidebar-top' => array('slave_id' => 'adoceansipilrftluvb', 'master_id' => 'X.WmYa.m8sO.1FT5ycY5kpBjz8JPGo9d03uU0HMJ6Z3.g7'),
	'single-bottom' => array('slave_id' => 'adoceansimjcijqfjla', 'master_id' => 'X.WmYa.m8sO.1FT5ycY5kpBjz8JPGo9d03uU0HMJ6Z3.g7'),
	'banderola' => array('slave_id' => 'adoceansiokpndomfbi', 'master_id' => 'X.WmYa.m8sO.1FT5ycY5kpBjz8JPGo9d03uU0HMJ6Z3.g7'),
	'sidebar-bottom' => array('slave_id' => 'adoceansiugjhnilncg', 'master_id' => 'X.WmYa.m8sO.1FT5ycY5kpBjz8JPGo9d03uU0HMJ6Z3.g7'),
	'single-comment' => array('slave_id' => 'adoceansirhqnqvesbb', 'master_id' => 'X.WmYa.m8sO.1FT5ycY5kpBjz8JPGo9d03uU0HMJ6Z3.g7'),
	'billboard' => array('slave_id' => 'adoceansioiheetogra', 'master_id' => 'X.WmYa.m8sO.1FT5ycY5kpBjz8JPGo9d03uU0HMJ6Z3.g7'),
	'floater' => array('slave_id' => 'adoceansiwcridrgsia', 'master_id' => 'X.WmYa.m8sO.1FT5ycY5kpBjz8JPGo9d03uU0HMJ6Z3.g7'),
),
's:za-delnicarje' => array(
	'sidebar-top' => array('slave_id' => 'adoceansisbgjpmmthm', 'master_id' => '.i9F9dZkPTJH0E8aXEuZnCwmIBcOWuMi5QxTwk_YNfj.67'),
	'single-bottom' => array('slave_id' => 'adoceansipcnpckgiml', 'master_id' => '.i9F9dZkPTJH0E8aXEuZnCwmIBcOWuMi5QxTwk_YNfj.67'),
	'banderola' => array('slave_id' => 'adoceansirgjogupkmb', 'master_id' => '.i9F9dZkPTJH0E8aXEuZnCwmIBcOWuMi5QxTwk_YNfj.67'),
	'billboard' => array('slave_id' => 'adoceansivopthirlbb', 'master_id' => '.i9F9dZkPTJH0E8aXEuZnCwmIBcOWuMi5QxTwk_YNfj.67'),
	'single-comment' => array('slave_id' => 'adoceansispgklvkqww', 'master_id' => '.i9F9dZkPTJH0E8aXEuZnCwmIBcOWuMi5QxTwk_YNfj.67'),
	'sidebar-bottom' => array('slave_id' => 'adoceansipaoqosefbv', 'master_id' => '.i9F9dZkPTJH0E8aXEuZnCwmIBcOWuMi5QxTwk_YNfj.67'),
	'floater' => array('slave_id' => 'adoceansiwprpjudmcs', 'master_id' => '.i9F9dZkPTJH0E8aXEuZnCwmIBcOWuMi5QxTwk_YNfj.67'),
),
);
/* end of AdOcean Configuration */
?>